learning_users/basic_app/urls.py
from django.conf.urls import url
from basic_app import views
from django.urls import path, include, re_path

#TEMPLATE URLs
app_name = 'basic_app'

urlpatterns = [
    re_path(r'^register/$',views.register,name='register'),
    re_path(r'^userLogin/$',views.userLogin,name='userLogin'),
]

learning_users/learning_users/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from basic_app import views

urlpatterns = [
    path('admin/', admin.site.urls),
    re_path(r'^$', views.index, name="index"),
    path('basic_app/',include('basic_app.urls')),
    re_path(r'^logout/$',views.userLogout,name='userLogout'),
    re_path(r'^special/',views.special,name='special')
]

learning_users/basic_app/models.py
from django.db import models
from django.contrib.auth.models import User

class userProfileInfo(models.Model):

    user = models.OneToOneField(User,on_delete=models.CASCADE)

    # additional stuff

    portfolioSite = models.URLField(blank=True)
    profilePic = models.ImageField(upload_to='profile_pics',blank=True)

    def __str__(self):
        return self.user.username

learning_users/basic_app/forms.py
from django import forms
from django.contrib.auth.models import User
from basic_app.models import userProfileInfo

class userForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput)
    class Meta():
        model = User
        fields = ('username','email','password')

class userProfileInfoForm(forms.ModelForm):
    class Meta():
        model = userProfileInfo
        fields = ('portfolioSite','profilePic')

learning_users/basic_app/views.py
from django.shortcuts import render
from basic_app.forms import userForm,userProfileInfoForm
from django.urls import reverse
from django.contrib.auth.decorators import login_required
from django.http import HttpResponseRedirect,HttpResponse
from django.contrib.auth import authenticate,login,logout
# Create your views here.
######################################### INDEX
def index(request):
    return render(request,'basic_app/index.html')
######################################### LogOut
@login_required
def userLogout(request):
    logout(request)
    return HttpResponseRedirect(reverse('index'))
######################################### Special
@login_required
def special(request):
    return HttpResponse("You are logged in, nice!")
######################################### REGISTER
def register(request):
    registered = False
    if request.method == "POST":
        userFormreg = userForm(data=request.POST)
        profileFormreg = userProfileInfoForm(data=request.POST)

        if userFormreg.is_valid() and profileFormreg.is_valid():
            user = userFormreg.save()
            user.set_password(user.password)
            user.save()

            profile = profileFormreg.save(commit=False)
            profile.user = user

            if 'profilePic' in request.FILES:
                profile.profile_pic = request.FILES['profilePic']

            profile.save()

            registered = True
        else:
            print("userFormreg.errors,profileFormreg.errors")
    else:
        userFormreg = userForm()
        profileFormreg = userProfileInfoForm()
    return render(request,'basic_app/registration.html',
                                                        {'userFormreg':userFormreg,
                                                        'profileFormreg':profileFormreg,
                                                        'registered':registered})
######################################### logIN
def userLogin(request):
    if request.method == "POST":
        username = request.POST.get('username')
        password = request.POST.get('password')

        user = authenticate(username=username,password=password)

        if user:
            if user.is_active:
                login(request,user)
                return HttpResponseRedirect(reverse('index'))

            else:
                return HttpResponse("Your account is inactive")
        else:
            print("Someone tried to log in and failed")
            print("Username:{} and password {}".format(username,password))
            return HttpResponse("invalid login details supplied")
    else:
        return render(request,'basic_app/login.html',{})

learning_users/templates/basic_app/base.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title></title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">
  </head>
  <body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
          <a class="navbar-brand" href="{%url 'index'%}">DJANGO</a>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
            <div class="navbar-nav">
              <a class="nav-link" href="{% url 'admin:index' %}">Admin</a>
              <a class="nav-link" href="{% url 'basic_app:register'%}">Register</a>
              {%if user.is_authenticated%}
              <a class="nav-link" href="{% url 'userLogout'%}">logout</a>
              {%else%}
              <a class="nav-link" href="{% url 'basic_app:userLogin'%}">login</a>
              {%endif%}
            </div>
          </div>
        </nav>
  {% block body_block %}
  {% endblock %}
  </body>
</html>

learning_users/templates/basic_app/index.html
<!DOCTYPE html>
{% extends "basic_app/base.html"%}
{% block body_block%}
  <p></p>

<div class="jumbotron">
  <h1>Django Level Five - User input</h1>
</div>

{%endblock%}

learning_users/templates/basic_app/login.html
<!DOCTYPE html>
{% extends "basic_app/base.html"%}
{% block body_block %}

<div class="jumbotron">

  <h1>Please Log in</h1>

  <form action="{%url 'basic_app:userLogin'%}" method="POST">

    {%csrf_token%}

    <label for="username">Username:</label>
    <input type="text" name="username" placeholder="Enter username:""">
    <label for="password">Type in your password</label>
    <input type="password" name="password">
    <input type="submit" name="" value="Log In">

  </form>

</div>


{%endblock%}

learning_users/templates/basic_app/registration.html
{%extends 'basic_app/base.html'%}

{% load static %}

{% block body_block%}

<div class="jumbotron">

    {% if registered %}
        <h1>Thank you for registering.</h1>
    {%else%}
        <h1>Register here!</h1>
        <h3>Fill out the form</h3>
        <p></p>
        <form method="post" enctype="multipart/form-data">

          {%csrf_token%}
          {{ userFormreg.as_p }}
          {{ profileFormreg.as_p }}

          <input type="submit" name="" value="Register">
        </form>

    {%endif%}

</div>

{%endblock%}